# PyTorch HandsON



| Story | Souce | Dataset | Description |
|[Story](https://www.pivotaltracker.com/story/show/188286656) | [Source](https://www.dataquest.io/blog/pytorch-for-beginners/) | | HandsOn PyTorch: Concepts, Foundations. Image Classification / DL Hello World|



#### Tensors

#### *Basics*

In [1]:
# Create a tensor
import torch
import numpy as np

In [2]:
ndarray = np.array([5,6,7])
t = torch.from_numpy(ndarray)
print(t)

tensor([5, 6, 7])


In [3]:
# Tensor attributes
print(t.shape)
print(t.dtype)
print(t.device)

torch.Size([3])
torch.int64
cpu


In [4]:
# tensor from python list
t = torch.tensor([4,5,6])
print(t)

tensor([4, 5, 6])


In [6]:
# Multidimensional tensors
ndarray = np.array([[0,1,2], [3,4,5], [6,7,8]])
t = torch.from_numpy(ndarray)
print(t)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [8]:
# Create tensor from other tensor
new_t = torch.rand_like(t, dtype=torch.float)
print(new_t)

tensor([[0.5918, 0.7959, 0.9727],
        [0.3018, 0.4787, 0.3407],
        [0.7760, 0.7772, 0.9809]])


In [9]:
# tensor defined by shape
m_shape = (5,5)
rand_t = torch.rand(m_shape)
print(rand_t)

tensor([[0.6399, 0.6116, 0.6234, 0.3105, 0.9939],
        [0.3810, 0.1028, 0.8208, 0.6227, 0.9113],
        [0.7369, 0.4527, 0.3370, 0.4176, 0.7238],
        [0.5750, 0.8508, 0.0394, 0.6655, 0.5500],
        [0.8593, 0.4417, 0.1527, 0.9768, 0.5052]])


#### *Operations*

In [11]:
zeros_tensor = torch.zeros((3,5))
print(zeros_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
# Indexing
