# PyTorch HandsON



| Story | Souce | Dataset | Description |
|-----|-----|------|------|
|[Story](https://www.pivotaltracker.com/story/show/188286656) | [Source](https://www.dataquest.io/blog/pytorch-for-beginners/) | |HandsOn PyTorch: Concepts, Foundations. Image Classification / DL Hello World |



#### Tensors

#### *Basics*

In [1]:
# Create a tensor
import torch
import numpy as np

In [4]:
ndarray = np.array([[5,6,7], [9,9,0]])
t = torch.from_numpy(ndarray)
print(t)

tensor([[5, 6, 7],
        [9, 9, 0]])


In [5]:
# Tensor attributes
print(t.shape)
print(t.dtype)
print(t.device)

torch.Size([2, 3])
torch.int64
cpu


In [6]:
# tensor from python list
t = torch.tensor([4,5,6])
print(t)

tensor([4, 5, 6])


In [7]:
# Multidimensional tensors
ndarray = np.array([[0,1,2], [3,4,5], [6,7,8]])
t = torch.from_numpy(ndarray)
print(t)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [8]:
# Create tensor from other tensor
new_t = torch.rand_like(t, dtype=torch.float)
print(new_t)

tensor([[0.9653, 0.0934, 0.2263],
        [0.6512, 0.8927, 0.2691],
        [0.3262, 0.8734, 0.8469]])


In [27]:
# tensor defined by shape
m_shape = (5,5)
rand_t = torch.rand(m_shape)
print(rand_t)
print(rand_t[2:4,4])
transposed0 = rand_t.T
print(transposed0)

tensor([[0.5363, 0.0052, 0.2228, 0.5017, 0.3272],
        [0.9200, 0.2067, 0.2469, 0.2594, 0.6021],
        [0.5544, 0.9606, 0.5000, 0.2944, 0.3701],
        [0.3453, 0.1347, 0.5223, 0.2454, 0.6699],
        [0.0472, 0.2297, 0.2207, 0.7118, 0.7677]])
tensor([0.3701, 0.6699])
tensor([[0.5363, 0.9200, 0.5544, 0.3453, 0.0472],
        [0.0052, 0.2067, 0.9606, 0.1347, 0.2297],
        [0.2228, 0.2469, 0.5000, 0.5223, 0.2207],
        [0.5017, 0.2594, 0.2944, 0.2454, 0.7118],
        [0.3272, 0.6021, 0.3701, 0.6699, 0.7677]])


#### *Operations*

In [10]:
zeros_tensor = torch.zeros((3,5))
print(zeros_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
# Indexing
print(zeros_tensor[1])
print(zeros_tensor[:,0])

tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0.])


In [26]:
# Transposing
transposed = zeros_tensor.T
print(transposed)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [29]:
# Product of tensors
ones_tensor = torch.ones(5,3)
print(ones_tensor)
product = torch.matmul(zeros_tensor, ones_tensor)
print(product)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### Data Loading

In [36]:
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

In [38]:
training_data = datasets.MNIST(root=".", train=True, download=True, transform=ToTensor())
test_data = datasets.MNIST(root=".", train=False, download=True, transform=ToTensor())

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████| 9912422/9912422 [00:03<00:00, 2622189.00it/s]


Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 401739.45it/s]


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████| 1648877/1648877 [00:00<00:00, 3546139.97it/s]


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 986869.50it/s]

Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw

